# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='arr_el',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('start_or_finish', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('length', models.TimeField()),
                ('hidden_index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('is_impossible', models.CharField(max_length=127)),
                ('members', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Event_description',
            },
        ),
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_work', models.TimeField()),
                ('finish_work', models.TimeField()),
                ('birth', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
