# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Static', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 5, 30, 11, 8, 53, 623703, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
