# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Static', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
