# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Static', '0002_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='test@test.test', max_length=254),
            preserve_default=False,
        ),
    ]
