# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Static', '0003_auto_20160407_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='particip_events',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='test',
        ),
    ]
