# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Static', '0005_event_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test_field',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
