# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Static', '0006_event_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='test_field',
        ),
        migrations.AddField(
            model_name='event',
            name='test_out',
            field=models.CharField(default='Testy', max_length=100),
            preserve_default=False,
        ),
    ]
