# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Static', '0007_auto_20160412_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='arr_el',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('start_or_finish', models.BooleanField()),
            ],
        ),
    ]
