# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Static', '0008_arr_el'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='test_out',
        ),
    ]
