# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Static', '0009_remove_event_test_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_impossible',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
